<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        const p = new Promise(function(resolve, reject) {
                setTimeout(function() {
                    let data = '数据获取成功'
                    resolve(data)
                }, 1000)
            })
            // 成功或者失败会调用Promise里的then()方法
            // 调用then方法 then方法返回的是promise对象，对象状态由回调函数的执行结果决定
            // 1.如果回调函数中返回的结果是 非promise 类型的属性，状态为成功，返回值为对象成功的值
        const result = p.then(value => {
                console.log(value)
                    // 1. 非Promise类型属性
                    // return "iiii"

                // 2.是Promise对象
                return new Promise((resolve, reject) => {
                        resolve('ok') // 返回是成功的则p.then方法返回的对象状态显示成功，值也是返回的成功的值
                    }) // 返回的是失败的则p.then方法返回的对象状态显示失败，值也是返回的失败的值
            },
            reason => {
                console.error(reason)
            })
        console.log(result)

        // Promise返回的是一个Promise对象，所以then方法可以链式调用 回调接着回调，解决回调地狱的问题
        p.then(value => {

        }).then(value => {

        })
    </script>
</body>

</html>